# Generated by Django 4.1.6 on 2023-02-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='images')),
                ('tag', models.CharField(choices=[('ELECTR', 'Electronics'), ('CLOTH', 'Clothes'), ('SPORT', 'Sports'), ('PET', 'Pet supplies'), ('SOFTW', 'Software'), ('HEALTH', 'Health')], max_length=120)),
            ],
        ),
    ]
