# Generated by Django 4.1.6 on 2023-02-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
