# Generated by Django 4.1.6 on 2023-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_description_product_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(default='No description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='No name', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='No short description', max_length=100),
        ),
    ]
