# Generated by Django 4.1.6 on 2023-02-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_price_alter_product_long_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='category',
        ),
    ]
