# Generated by Django 4.1.6 on 2023-02-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_options_rename_tag_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('mapImage', models.ImageField(upload_to='shopMapImages')),
                ('link', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
